# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.0"

default_platform :android

platform :android do

    version = 83
    versionInstant = 82


    before_all do
        # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    end

    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end


    desc "Deploy app to play store alpha channel"
    lane :deployAlpha do |options|

        gradle(task: 'clean')
        gradle(
              task: ":app-apk:bundleInstalledRelease",
              properties: {
                  'versionCode' => version
              }
        )

        supply(
            package_name: "com.surrus.galwaybus",
            track: "alpha",
            aab: "app-apk/build/outputs/bundle/installedRelease/app-apk.aab",
            skip_upload_apk: true,
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true
        )
    end


    lane :deployInternalTest do |options|

        gradle(task: 'clean')
        gradle(
              task: ":app-apk:bundleInstalledRelease",
              properties: {
                  'versionCode' => version
              }
       )

        supply(
            package_name: "com.surrus.galwaybus",
            track: "internal",
            aab: "app-apk/build/outputs/bundle/installedRelease/app-apk.aab",
            skip_upload_apk: true,
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true
        )
    end


    lane :buildApp do |options|
        gradle(task: 'clean')
        gradle(
              task: ":app-apk:bundleInstalledRelease",
              properties: {
                  'versionCode' => version
              }
        )
    end

    lane :buildAppApk do |options|
        gradle(task: 'clean')
        gradle(
              task: ":app-apk:assembleInstalledRelease",
              properties: {
                  'versionCode' => version
              }
        )
    end

    lane :buildInstantApp do |options|
        gradle(task: 'clean')
        gradle(
              task: ":app-apk:bundleInstantRelease",
              properties: {
                  'versionCode' => versionInstant
              }
        )
    end


    desc "Promote app from alpha to production in Play Store"
    lane :promoteAppToProd do |options|

        supply(
            package_name: "com.surrus.galwaybus",
            track: "internal",
            track_promote_to: "production",
            skip_upload_apk: true,
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true
        )
    end


    desc "Generate app screenshots that will be uploaded to play store"
    lane :screenshots do |options|

        gradle(
              task: "assembleDebug assembleDebugAndroidTest"
        )

        screengrab(
            locales: ['en-US'],
            clear_previous_screenshots: true,
            app_package_name: "com.surrus.galwaybus",
            use_tests_in_packages: ['com.surrus.galwaybus.screenshots'],
            app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
            tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
        )
    end





  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
